# generated by datamodel-codegen:
#   filename:  connection.schema
#   timestamp: 2025-05-13T00:35:33+00:00

"""
VDA5050プロトコルにおける接続状態(connection)のデータモデル定義モジュール。

このモジュールは、AGV(無人搬送車)とMQTTブローカー間の接続状態を表すJSON構造を
Pydanticモデルとして定義しています。ブローカーとAGV間の接続が切断された場合、
最終意志メッセージ(Last Will)としてこの情報が配信されます。

参照: VDA5050 v2.1.0 - セクション6.14 Topic "connection"
"""

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field


class ConnectionState(Enum):
    """
    AGVとブローカー間の接続状態を表す列挙型。
    
    ONLINE: AGVとブローカー間の接続がアクティブ
    OFFLINE: AGVとブローカー間の接続が調整された方法でオフラインになった
    CONNECTIONBROKEN: AGVとブローカー間の接続が予期せず終了した
    """
    ONLINE = 'ONLINE'
    OFFLINE = 'OFFLINE'
    CONNECTIONBROKEN = 'CONNECTIONBROKEN'


class Connection(BaseModel):
    """
    接続状態メッセージの全体構造を表すルートモデル。
    
    ヘッダー情報とAGVとブローカー間の接続状態を含みます。
    このメッセージはMQTTの「最終意志」機能を使用して、
    AGVとブローカー間の接続が予期せず失われた場合に配信されます。
    """
    headerId: int = Field(
        ...,
        description='Header ID of the message. The headerId is defined per topic and incremented by 1 with each sent (but not necessarily received) message.',
    )
    timestamp: datetime = Field(
        ...,
        description='Timestamp in ISO8601 format (YYYY-MM-DDTHH:mm:ss.ssZ).',
        examples=['1991-03-11T11:40:03.12Z'],
    )
    version: str = Field(
        ...,
        description='Version of the protocol [Major].[Minor].[Patch]',
        examples=['1.3.2'],
    )
    manufacturer: str = Field(..., description='Manufacturer of the AGV.')
    serialNumber: str = Field(..., description='Serial number of the AGV.')
    connectionState: ConnectionState = Field(
        ...,
        description='ONLINE: connection between AGV and broker is active. OFFLINE: connection between AGV and broker has gone offline in a coordinated way. CONNECTIONBROKEN: The connection between AGV and broker has unexpectedly ended.',
    )
