# generated by datamodel-codegen:
#   filename:  instantActions.schema
#   timestamp: 2025-05-13T00:35:34+00:00

"""
VDA5050プロトコルにおける即時アクション(instantActions)のデータモデル定義モジュール。

このモジュールは、マスターコントロールからAGV(無人搬送車)へ送信される即時アクションのJSON構造を
Pydanticモデルとして定義しています。即時アクションは、AGVが現在の注文(order)を中断することなく
即座に実行すべきアクションを指定するために使用されます。

参照: VDA5050 v2.1.0 - セクション6.9 Topic: "instantActions" (from master control to AGV)
"""

from __future__ import annotations

from datetime import datetime
from typing import List

from pydantic import BaseModel, Field

from pydantic_models.common import Action


class InstantActions(BaseModel):
    """
    即時アクションメッセージの全体構造を表すルートモデル。
    
    マスターコントロールからAGVに送信され、現在の注文とは独立して
    即座に実行すべきアクションのリストを含みます。例えば、AGVの一時停止や
    再開、シグナルの有効化などのために使用されます。
    """
    headerId: int = Field(
        ...,
        description='headerId of the message. The headerId is defined per topic and incremented by 1 with each sent (but not necessarily received) message.',
        title='headerId',
    )
    timestamp: datetime = Field(
        ...,
        description='Timestamp in ISO8601 format (YYYY-MM-DDTHH:mm:ss.ffZ).',
        examples=['1991-03-11T11:40:03.12Z'],
        title='timestamp',
    )
    version: str = Field(
        ...,
        description='Version of the protocol [Major].[Minor].[Patch]',
        examples=['1.3.2'],
        title='Version',
    )
    manufacturer: str = Field(..., description='Manufacturer of the AGV')
    serialNumber: str = Field(..., description='Serial number of the AGV.')
    actions: List[Action]
