# generated by datamodel-codegen:
#   filename:  visualization.schema
#   timestamp: 2025-05-13T00:35:34+00:00

"""
VDA5050プロトコルにおける可視化(visualization)のデータモデル定義モジュール。

このモジュールは、AGV(無人搬送車)から可視化システムへ送信される位置・速度情報のJSON構造を
Pydanticモデルとして定義しています。通常のstate情報よりも高頻度で位置情報を送信することで、
リアルタイムに近い可視化を実現します。

参照: VDA5050 v2.1.0 - セクション6.13 Topic "visualization"
"""

from __future__ import annotations

from datetime import datetime
from typing import Optional

from pydantic import BaseModel, Field


class AgvPosition(BaseModel):
    """
    可視化目的のAGV位置情報を表すモデル。
    
    座標(x, y)、向き(theta)、マップID、位置の初期化状態、
    位置精度情報などを含みます。state情報のAgvPositionと同様の構造です。
    """
    x: float
    y: float
    theta: float
    mapId: str
    positionInitialized: bool = Field(
        ...,
        description='True if the AGVs position is initialized, false, if position is not initizalized.',
    )
    localizationScore: Optional[float] = Field(
        None,
        ge=0.0,
        le=1.0,
        description='Localization score for SLAM based vehicles, if the AGV can communicate it.',
    )
    deviationRange: Optional[float] = Field(
        None,
        description='Value for position deviation range in meters. Can be used if the AGV is able to derive it.',
    )


class Velocity(BaseModel):
    """
    可視化目的のAGV速度情報を表すモデル。
    
    x方向速度、y方向速度、回転速度(z軸周り)を含みます。
    車両座標系での値です。state情報のVelocityと同様の構造です。
    """
    vx: Optional[float] = None
    vy: Optional[float] = None
    omega: Optional[float] = None


class Visualization(BaseModel):
    """
    可視化メッセージの全体構造を表すルートモデル。
    
    ヘッダー情報、AGVの位置と速度の情報を含みます。
    このトピックは可視化目的のみで使用され、通常のstate情報よりも
    高頻度で送信されることが期待されます。
    """
    headerId: Optional[int] = Field(
        None,
        description='headerId of the message. The headerId is defined per topic and incremented by 1 with each sent (but not necessarily received) message.',
    )
    timestamp: Optional[datetime] = Field(
        None,
        description='Timestamp in ISO8601 format (YYYY-MM-DDTHH:mm:ss.ffZ).',
        examples=['1991-03-11T11:40:03.12Z'],
    )
    version: Optional[str] = Field(
        None,
        description='Version of the protocol [Major].[Minor].[Patch]',
        examples=['1.3.2'],
    )
    manufacturer: Optional[str] = Field(None, description='Manufacturer of the AGV')
    serialNumber: Optional[str] = Field(None, description='Serial number of the AGV.')
    agvPosition: Optional[AgvPosition] = Field(
        None, description='The AGVs position', title='agvPosition'
    )
    velocity: Optional[Velocity] = Field(
        None, description='The AGVs velocity in vehicle coordinates', title='velocity'
    )
